JENKINS_TESTTYPES:
  - bareos-client-only+bareos-universal-client+bareos-postgresql
  - univention-bareos

OS:
  CentOS:
    "7":
      TYPE: rpm
      IMAGE: centos7
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos

  win:
    cross:
      TYPE: win
      STAGES:
        - win-32-release
        - win-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-10-32
         - windows-10-64
