<?php

/**
 *
 * bareos-webui - Bareos Web-Frontend
 *
 * @link      https://github.com/bareos/bareos for the canonical source repository
 * @copyright Copyright (c) 2022-2022 Bareos GmbH & Co. KG (http://www.bareos.org/)
 * @license   GNU Affero General Public License (http://www.gnu.org/licenses/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

echo $this->render('_header.phtml');
?>

<?php if(!$this->acl_alert) : ?>

<div class="panel-heading">
   <h3 class="panel-title"><?php echo $this->translate("Subscription Status"); ?></h3>
</div>

<div>
<a href=https://www.bareos.com/product/subscription/  target="_blank">Get information about the Bareos Subscription model.</a>
</div>
<div>
<a href=/subscription/status>Download your Bareos Subscription status (JSON).</a>
</div>

<div class="panel-body">
<pre class="dird-messages" style="height: 500px; font-size: 8pt;">
<code>
<?php echo $this->escapeHtml($this->directorOutput); ?>
</code>
</pre>
</div>

<?php
echo $this->render('_footer.phtml');
?>

<?php endif; ?>
